Update rest-client to 2.0 to fix ssl cipher issue
Requests fail under Ruby >= 2.4.x due to weirdness with openssl1.1.
Error message is:

    KeyError: key not found: :ciphers

This is fixed in rest-client 2.x but the gemspec pins to 1.8.x.

See https://github.com/rest-client/rest-client/issues/569 for
background.